# Generated by Django 4.2.24 on 2025-09-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('sesion', models.IntegerField()),
                ('programa', models.CharField(max_length=500)),
                ('estudiante', models.CharField(max_length=500)),
                ('modalidad', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('resolucion', models.CharField(max_length=50)),
                ('programa_profesor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Compilado',
                'verbose_name_plural': 'Compilados',
                'db_table': 'compilado',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('facultad', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docentes',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('legajo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=5)),
                ('identificacion', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_institucional', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('estudiante', models.CharField(max_length=20)),
                ('facultad', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=100)),
                ('regionalizacion', models.CharField(max_length=1)),
                ('sede', models.CharField(max_length=50)),
                ('jornada', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiantes',
            },
        ),
    ]
