# Generated by Django 4.2.24 on 2025-10-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compilado',
            options={},
        ),
        migrations.AlterField(
            model_name='compilado',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compilados_dirigidos', to='projects.docente'),
        ),
        migrations.AlterField(
            model_name='compilado',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compilados', to='projects.estudiante'),
        ),
        migrations.AlterModelTable(
            name='compilado',
            table=None,
        ),
    ]
