# Generated by Django 4.2.24 on 2025-12-18 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_compilado_options_alter_compilado_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha de inicio del proyecto')),
                ('expiry_date', models.DateField(blank=True, help_text='Fecha de vencimiento del proyecto', null=True)),
                ('sesion', models.IntegerField(help_text='Número de sesión')),
                ('resolucion', models.IntegerField(blank=True, help_text='Número de resolución', null=True)),
                ('modalidad', models.CharField(choices=[('PRACTICA', 'Práctica profesional'), ('INVESTIGACION', 'Investigación'), ('COTERMINAL', 'Plan Coterminal'), ('PROFUNDIZACION', 'Profundización'), ('TRABAJO_SOCIAL', 'Trabajo Social')], max_length=20)),
                ('title', models.CharField(help_text='Título del proyecto', max_length=500)),
                ('department', models.CharField(help_text='Departamento académico', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=15)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('codirector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_codirected', to='projects.docente')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_directed', to='projects.docente')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='miembro', max_length=20)),
            ],
            options={
                'db_table': 'projects_students',
            },
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='periodo',
        ),
        migrations.DeleteModel(
            name='Compilado',
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_legajo', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.estudiante'),
        ),
        migrations.AddField(
            model_name='projectstudent',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['department'], name='projects_departm_0915a7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
    ]
