# Generated by Django 4.2.24 on 2025-12-18 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_projectstudent_remove_estudiante_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstudent',
            name='estudiante',
            field=models.ForeignKey(db_column='estudiante_legajo', on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='projects.estudiante'),
        ),
    ]
