# Generated by Django 4.2.24 on 2026-01-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectstudent_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='departamento',
            field=models.CharField(choices=[('CONSTRUCCION', 'Arquitectura y Construcción'), ('VIAS_Y_TRANSPORTE', 'Vías y Transporte'), ('HIDRAULICA', 'Hidráulica'), ('GEOTECNIA', 'Geotecnia'), ('ESTRUCTURAS', 'Estructuras'), ('ING_AMBIENTAL_SANITARIA', 'Ing. Ambiental y Sanitaria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('CONSTRUCCION', 'Arquitectura y Construcción'), ('VIAS_Y_TRANSPORTE', 'Vías y Transporte'), ('HIDRAULICA', 'Hidráulica'), ('GEOTECNIA', 'Geotecnia'), ('ESTRUCTURAS', 'Estructuras'), ('ING_AMBIENTAL_SANITARIA', 'Ing. Ambiental y Sanitaria')], help_text='Departamento académico', max_length=50),
        ),
    ]
